### ISSUE TITLE
Respect trailing whitespace on toggle

### ISSUE THREAD

**Issue by gaponcode** [PKief/vscode-markdown-checkbox#11]
When toggling a checkbox, remaining whitespace not respected and removed.
_Please note the whitespace on first lines!_

**This**
```md
- [ ] Checkbox  
  This is on second line
- [ ] Checkbox
```
**become this when toggle the first Checkbox**
```md
- [ ] Checkbox [2019-03-03]
  This is on second line
- [ ] Checkbox
```

**Comment by PKief** [comment]
Hi @gaponcode, thanks for asking, I've never noticed that 😄 
Do you expect to have the whitespaces after the date like

```
- [ ] Checkbox [2019-03-03]          
```
?

**Comment by DoCode** [comment]
@PKief I think the best is that always when a date is added or not, it should preserve the whitespace at end of the line for explicit MarkDown linebreaks.

Note: The same 'trimming' is taken, when NO date is added and only the checkbox is toggled! Here the same, the whitespace should be preserved.

Thanks for your fast response! :-)

**Comment by PKief** [comment]
I changed the behavior to respect the whitespaces at the end of the line. You can find the updated version of this extension on the marketplace 👍
