### ISSUE TITLE
I would like to change the datestamp format

### ISSUE THREAD

**Issue by robertmarkbram** [PKief/vscode-markdown-checkbox#15]
Particularly I want a timestamp. 

Love the extension.. 

Rob
:)

**Comment by PKief** [comment]
Hi @robertmarkbram, I added this feature to the extension and an update will be coming very soon (probably tomorrow). Then, you will be able to customize the date in the user settings like this:

```
"markdown-checkbox.dateFormat": "YYYY-MM-DD"
```

Have a look at this documentation for more information about customization patterns:
https://momentjs.com/docs/#/parsing/string-format/

**Comment by mjsisley** [comment]
Great Extension and thank you!

Would you mind adding more flexibility to the date format? I ultimately want the following format "[[arbitrary.text.2022.11.14]]" Basically I'm hoping to be able to add a string wrapper around the date format used by Moment.

I'm hoping to use the format to generate backlinks (specifically through Dendron PKM extension). This would allow todos distributed throughout many files and various projects will when checked off via this extension automatically generate backlinks for a date (so are all automatically collected via their backlink/graph interface).

Thanks again.
