### ISSUE TITLE
Recently started adding checkboxes without user intervention

### ISSUE THREAD

**Issue by SimplGy** [PKief/vscode-markdown-checkbox#18]
I had to uninstall this today; it recently started adding checkboxes apparently without user intervention. This happened a few times. I'm guessing some interaction with VSCode version + Linux Version. Was working fine for a few months before this.

**Comment by SimplGy** [comment]
Is it possible it's capturing keystrokes while I'm focused on another window?

**Comment by PKief** [comment]
I haven't experienced anything like this before, actually the keystroke should always take place in the focused window. Could be a Linux-specific problem with VS Code.

**Comment by PKief** [comment]
I'm closing this now. We need more information to elaborate on this issue and it's not possible to reproduce it.
