### ISSUE TITLE
Multi-line operations

### ISSUE THREAD

**Issue by akashagarwal7** [PKief/vscode-markdown-checkbox#23]
First - Love the extension!

Title explains it all. Would love to have the ability to mark multiple lines as checkboxes/toggle checkboxes, based on selection :)

**Comment by PKief** [comment]
Sounds like an exciting feature. Let's see when I find the time to implement it. Thanks for the suggestion :)

**Comment by PKief** [comment]
Will be most likely the follow-up of #22.
