### ISSUE TITLE
Timestamp causes "No link definition found" warning

### ISSUE THREAD

**Issue by blonewolfs** [PKief/vscode-markdown-checkbox#46]
Thank you for the great plugin.
I found a problem when using the "Date when checked" option. The date is enclosed in square brackets `[]` which causes VS Code to assume it is the beginning of a link reference, throwing the "No link definition found" warning.
Is it possible to change the brackets to some other characters such as parenthesis `()` that won't confuse VS Code? If this user configurable, that would be ideal since I could see different linters complaining about different characters; or, just plain different user preferences.

**Comment by m-paternostro** [comment]
Ditto on "Thank you for the great plugin." ;-)

I ran into this one too. Using parenthesis would work for me too, if adding a configuration is too much work.

**Comment by m-paternostro** [comment]
I just pushed a [PR](https://github.com/PKief/vscode-markdown-checkbox/pull/50) with a suggestion of a fix for this issue. I hope it helps.
