### ISSUE TITLE
Option to disable checkbox info on status bar

### ISSUE THREAD

**Issue by mainczjs** [PKief/vscode-markdown-checkbox#8]
Hi there,

I really like using your extension. But I also like a clean status bar and I was missing an option to disable the checkbox info there. Is this something you could consider for a future version? :pray:

**Comment by PKief** [comment]
This option should definitely exist. I'll implement it and update the extension soon. 👍

**Comment by PKief** [comment]
@mainczjs With the latest update you can control the visibility of the status bar item with the following setting:

```json
"markdown-checkbox.showStatusBarItem": false
```

**Comment by mainczjs** [comment]
That was quick, thank you so much! Already added it to my config! 👍
